name: Build & Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build JAR with Gradle
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle (no tests)
        run: ./gradlew build -x test

      - name: Configure AWS CLI for MinIO
        run: |
          aws configure set aws_access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.MINIO_SECRET_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.output json

      - name: Supprimer l'ancienne version du JAR sur MinIO
        run: |
          if aws --endpoint-url ${{ secrets.MINIO_ENDPOINT }} s3 ls s3://artifacts/lapinback-latest.jar; then
            aws --endpoint-url ${{ secrets.MINIO_ENDPOINT }} s3 rm s3://artifacts/lapinback-latest.jar
          fi

      - name: Upload JAR to MinIO
        run: |
          aws --endpoint-url ${{ secrets.MINIO_ENDPOINT }} s3 cp build/libs/*.jar s3://artifacts/lapinback-latest.jar

  dockerize-and-push:
    name: Docker Build & Push
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS CLI for MinIO
        run: |
          aws configure set aws_access_key_id ${{ secrets.MINIO_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.MINIO_SECRET_KEY }}
          aws configure set default.region us-east-1
          aws configure set default.output json

      - name: Download JAR from MinIO
        run: |
          mkdir -p build/libs
          aws --endpoint-url ${{ secrets.MINIO_ENDPOINT }} s3 cp s3://artifacts/lapinback-latest.jar build/libs/lapinback-latest.jar

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t dubbelf/lapinback:latest .

      - name: Push Docker image
        run: docker push dubbelf/lapinback:latest
